name: Test Find Lowest Number
on: [push]
jobs:
  automated_test:
    name: Automated Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      # Test Case 1: File with 10 numbers
      - name: Run Test 1 - File with 10 numbers
        run: python find_lowest_number.py test-data/test1_input.txt test1_output.txt
        
      - name: Verify Test 1 Results
        run: diff test-data/test1_expected.txt test1_output.txt
        
      # Test Case 2: File with 1 number
      - name: Run Test 2 - File with 1 number
        run: python find_lowest_number.py test-data/test2_input.txt test2_output.txt
        
      - name: Verify Test 2 Results
        run: diff test-data/test2_expected.txt test2_output.txt
        
      # Test Case 3: Empty file
      - name: Run Test 3 - Empty file
        run: python find_lowest_number.py test-data/test3_input.txt test3_output.txt
        
      - name: Verify Test 3 Results
        run: diff test-data/test3_expected.txt test3_output.txt
